live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "full"

[font]
size = 10.0

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

# Uncomment to use an alternative clipboard provider like wl-clipboard if available
#ref: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#clipboard:
#  action: copy
#  command:
#    program: wl-copy
#    args: []

