call plug#begin()
Plug 'dense-analysis/ale'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'     " Easy commenting/uncommenting
Plug 'airblade/vim-gitgutter'   " Git change indicators in the gutter
Plug 'neoclide/coc.nvim', {'branch': 'release'}  " LSP client (coc.nvim)
Plug 'junegunn/seoul256.vim'
call plug#end()

syntax on
color seoul256-light

set nonu                                      " show the actual line number
set hidden
set nowrap                                  " no wrapping
set showmatch                               " highlight matching brackets
set hlsearch                                " highlight search results
set fileencoding=utf-8
set showbreak=↪                             " symbol to show wrapped lines
set visualbell noerrorbells                 " annoying bells
set history=500                             " undo history
set undofile                                " persistent undo
set expandtab                               " spaces are better than tabs
set shiftwidth=4                            " 4 spaces per auto indent
set autoindent                              " auto indent blocks
set tabstop=4                               
set softtabstop=4
set mouse=a                                 " mouse clicking
set noswapfile                              " no useless swap files
set scrolloff=8                             " dont go all the way down before scrolling
" set colorcolumn=80
set signcolumn=no                          " show the sign column on the lhs
set re=0

if has('mac')
    set clipboard=unnamed
else
    set clipboard=unnamedplus
endif

filetype plugin on

" Airline theme
" let g:airline_theme='base16'

" netrw
let g:netrw_liststyle=3                     " tree view
let g:netrw_banner=0                        " no stupid banner
let g:netrw_browse_split=0                  " open new files in a new buffer in the previous window

" MAPPINGS
let mapleader = ' '
nnoremap ; :
xnoremap ; :

nnoremap H 0
xnoremap H 0
nnoremap L $
xnoremap L $

" window management
" nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 30<CR>  " open file tree on lhs at size 30
nnoremap <leader>t :Ex<CR>

" open my vimrc
nnoremap<leader>rc :e $MYVIMRC<CR>

" quick source
nnoremap <leader><CR> :w<bar>:so %<CR> " save and source

" switch buffers with arrow keys
nnoremap <Left> :bp<CR>
nnoremap <Right> :bn<CR>

" Find and replace
nnoremap <C-H> :%s/
xnoremap <C-H> :s/

" File search with fzf and ripgrep
nnoremap <leader>f :Files<CR>

" Clear annoying and persistent highlighting after search
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :<C-U>nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

" Keep cursor position after yanking
nnoremap y myy
xnoremap y myy

" maintain cursor position after exiting and re-opening a file
autocmd BufReadPost * if @% !~# '\.git[\/\\]COMMIT_EDITMSG$' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif 

" Ignore certain files and folders when globing
set wildignore+=*.o,*.obj,*.dylib,*.bin,*.dll,*.exe
set wildignore+=*/.git/*,*/.svn/*,*/__pycache__/*,*/build/**
set wildignore+=*.jpg,*.png,*.jpeg,*.bmp,*.gif,*.tiff,*.svg,*.ico
set wildignore+=*.pyc,*.pkl
set wildignore+=*.DS_Store
set wildignore+=*.aux,*.bbl,*.blg,*.brf,*.fls,*.fdb_latexmk,*.synctex.gz,*.xdv
set wildignorecase  " ignore file and dir name cases in cmd-completionf

au BufNewFile,BufRead Jenkinsfile setf groovy " Jenkinsfile syntax highlighting
