call plug#begin()
" Searching
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Git
Plug 'tpope/vim-fugitive'

" Tabline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Themes
Plug 'lifepillar/vim-solarized8'
" Plug 'dlarocque/cider.vim'
" Plug 'chriskempson/base16-vim'
" Plug 'nordtheme/vim'
call plug#end()

set termguicolors

syntax on
color solarized8
set background=dark

set nu                                      " show the actual line number
set hidden
set nowrap                                  " no wrapping
set showmatch                               " highlight matching brackets
set hlsearch                                " highlight search results
set fileencoding=utf-8
set showbreak=↪                             " symbol to show wrapped lines
set visualbell noerrorbells                 " annoying bells
set history=500                             " undo history
set undofile                                " persistent undo
set expandtab                               " spaces are better than tabs
set shiftwidth=2                            " 4 spaces per auto indent
set autoindent                              " auto indent blocks
set tabstop=2                               
set softtabstop=2
set mouse=a                                 " mouse clicking
set scrolloff=8                             " dont go all the way down before scrolling
" set colorcolumn=80
set signcolumn=no                          " show the sign column on the lhs
set re=0

if has('mac')
    set clipboard=unnamed
else
    set clipboard=unnamedplus
endif

filetype plugin on

set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" Airline theme
" let g:airline_theme='base16'

" netrw
let g:netrw_liststyle=3                     " tree view
let g:netrw_banner=0                        " no stupid banner
let g:netrw_browse_split=0                  " open new files in a new buffer in the previous window

" MAPPINGS
let mapleader = ' '
nnoremap ; :
xnoremap ; :

nnoremap H 0
xnoremap H 0
nnoremap L $
xnoremap L $

" window management
" nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 30<CR>  " open file tree on lhs at size 30
nnoremap <leader>t :Ex<CR>

" open my vimrc
nnoremap <leader>rc :e $MYVIMRC<CR>

" quick source
nnoremap <leader><CR> :w<bar>:so %<CR> " save and source

" switch buffers with arrow keys
nnoremap <Left> :bp<CR>
nnoremap <Right> :bn<CR>

" Find and replace
nnoremap <C-H> :%s/
xnoremap <C-H> :s/

" File search with fzf and ripgrep
nnoremap <leader>ff :Files<CR>
nnoremap <leader>fh :Files ~<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>fs :RG<CR>
nnoremap <leader>fw :RG <C-R><C-W><CR>
nnoremap <leader>fc :Commits<CR>

let g:fzf_preview_window = ['down,70%,border-top', 'ctrl-/']

" Enable per-command history.
" Pressing <Up> will show previous fzf queries for that command.
let g:fzf_history_dir = '~/.local/share/fzf-history'

" Clear annoying and persistent highlighting after search
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :<C-U>nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

" Keep cursor position after yanking
nnoremap y myy
xnoremap y myy

" maintain cursor position after exiting and re-opening a file
autocmd BufReadPost * if @% !~# '\.git[\/\\]COMMIT_EDITMSG$' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif 

" Ignore certain files and folders when globing
set wildignore+=*.o,*.obj,*.dylib,*.bin,*.dll,*.exe
set wildignore+=*/.git/*,*/.svn/*,*/__pycache__/*,*/build/**
set wildignore+=*.jpg,*.png,*.jpeg,*.bmp,*.gif,*.tiff,*.svg,*.ico
set wildignore+=*.pyc,*.pkl
set wildignore+=*.DS_Store
set wildignore+=*.aux,*.bbl,*.blg,*.brf,*.fls,*.fdb_latexmk,*.synctex.gz,*.xdv
set wildignorecase  " ignore file and dir name cases in cmd-completion

au BufNewFile,BufRead Jenkinsfile setf groovy " Jenkinsfile syntax highlighting
