sync_address = ""
auto_sync = false
update_check = false

db_path = "~/.local/share/atuin/history.db"
search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "session"

style = "compact"
show_preview = true
inline_height = 20
invert = false
show_help = true
exit_mode = "return-original"
keymap_mode = "emacs"

history_filter = [
  "^secret-cmd",
  "^password",
]
